---
- name: Set up Controller Server
  hosts: all
  become: yes
  vars_files:
    - ../vars/secrets.yml 

- import_playbook: system_setup.yml
- import_playbook: tailscale_setup.yml
- import_playbook: git_setup.yml
- import_playbook: ssh_setup.yml
- import_playbook: initial_setup.yml
- import_playbook: app_server_setup.yml
- import_playbook: connection_check_setup.yml
